import Head from 'next/head'
import useStore from '@/store/main.store' // https://nextjs.org/docs/advanced-features/module-path-aliases
import { motion } from 'framer-motion'

export default function Home() {
  const state = useStore()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={'m-[22px]'}>
        <motion.h1>Hello {state.members}!</motion.h1>
        <motion.button
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          className='bg-green-500 text-white p-1 mt-4'
          onClick={() => state.update(Math.random())}
          drag
          dragConstraints={{
            top: -50,
            left: -50,
            right: 50,
            bottom: 50,
          }}>
          Update
        </motion.button>
      </main>
    </div>
  )
}
